workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.24.0
      java: 17
    scripts:
      - name: Clone llama.cpp
        script: |
          cd android/app/src/main/cpp
          git clone --branch b4547 --depth 1 https://github.com/ggerganov/llama.cpp.git

      - name: Get Flutter packages
        script: flutter pub get

      - name: Flutter doctor
        script: flutter doctor -v

      - name: Build APK (Release)
        script: flutter build apk --release --verbose

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
